import { Company } from '../types/company';

// Expanded company data with more companies
export const generateExpandedCompanies = (): Company[] => {
  const companies: Company[] = [
    {
      id: 'company_1',
      name: 'Acme Corp',
      description: 'A global leader in widgets and gadgets.',
      industry: 'Manufacturing',
      size: '10,000+ employees',
      founded: '1980',
      headquarters: 'New York, USA',
      website: 'https://acme.com',
      logo: 'https://logo.clearbit.com/acme.com',
      employees: 12000,
      revenue: '$2B',
      type: 'Public',
      specialties: ['Widgets', 'Gadgets'],
      benefits: ['Health insurance', '401k'],
      culture: ['Innovative', 'Global'],
      technologies: ['Java', 'SAP'],
      locations: [{ city: 'New York', state: 'NY', country: 'USA', type: 'Headquarters' }],
      socialMedia: { linkedin: '', twitter: '' },
      ratings: { overall: 4.1, culture: 4.0, workLifeBalance: 4.0, careerGrowth: 4.1, compensation: 4.0, management: 4.0, totalReviews: 1000 },
      contactInfo: { email: '', phone: '' },
      scrapedAt: new Date().toISOString(),
      source: 'Hardcoded'
    },
    {
      id: 'company_2',
      name: 'BetaSoft',
      description: 'Software solutions for modern businesses.',
      industry: 'Software',
      size: '1,000+ employees',
      founded: '2005',
      headquarters: 'San Francisco, USA',
      website: 'https://betasoft.com',
      logo: 'https://logo.clearbit.com/betasoft.com',
      employees: 1500,
      revenue: '$300M',
      type: 'Private',
      specialties: ['SaaS', 'Cloud'],
      benefits: ['Remote work', 'Stock options'],
      culture: ['Agile', 'Collaborative'],
      technologies: ['Python', 'AWS'],
      locations: [{ city: 'San Francisco', state: 'CA', country: 'USA', type: 'Headquarters' }],
      socialMedia: { linkedin: '', twitter: '' },
      ratings: { overall: 4.3, culture: 4.2, workLifeBalance: 4.1, careerGrowth: 4.2, compensation: 4.1, management: 4.0, totalReviews: 500 },
      contactInfo: { email: '', phone: '' },
      scrapedAt: new Date().toISOString(),
      source: 'Hardcoded'
    },
    {
      id: 'company_3',
      name: 'Gamma Health',
      description: 'Healthcare innovation for the 21st century.',
      industry: 'Healthcare',
      size: '5,000+ employees',
      founded: '1995',
      headquarters: 'London, UK',
      website: 'https://gammahealth.com',
      logo: 'https://logo.clearbit.com/gammahealth.com',
      employees: 6000,
      revenue: '$1B',
      type: 'Public',
      specialties: ['Medical Devices'],
      benefits: ['Health insurance'],
      culture: ['Caring', 'Innovative'],
      technologies: ['C++', 'IoT'],
      locations: [{ city: 'London', state: '', country: 'UK', type: 'Headquarters' }],
      socialMedia: { linkedin: '', twitter: '' },
      ratings: { overall: 4.0, culture: 4.0, workLifeBalance: 3.9, careerGrowth: 4.0, compensation: 3.9, management: 4.0, totalReviews: 800 },
      contactInfo: { email: '', phone: '' },
      scrapedAt: new Date().toISOString(),
      source: 'Hardcoded'
    },
    {
      id: 'company_4',
      name: 'Delta Retail',
      description: 'Retail chain with a global presence.',
      industry: 'Retail',
      size: '20,000+ employees',
      founded: '1970',
      headquarters: 'Berlin, Germany',
      website: 'https://deltaretail.com',
      logo: 'https://logo.clearbit.com/deltaretail.com',
      employees: 25000,
      revenue: '$5B',
      type: 'Public',
      specialties: ['Retail', 'E-commerce'],
      benefits: ['Employee discount'],
      culture: ['Customer-focused'],
      technologies: ['JavaScript', 'Oracle'],
      locations: [{ city: 'Berlin', state: '', country: 'Germany', type: 'Headquarters' }],
      socialMedia: { linkedin: '', twitter: '' },
      ratings: { overall: 3.8, culture: 3.7, workLifeBalance: 3.8, careerGrowth: 3.7, compensation: 3.8, management: 3.7, totalReviews: 1200 },
      contactInfo: { email: '', phone: '' },
      scrapedAt: new Date().toISOString(),
      source: 'Hardcoded'
    },
    {
      id: 'company_5',
      name: 'Epsilon Energy',
      description: 'Renewable energy for a sustainable future.',
      industry: 'Energy',
      size: '2,000+ employees',
      founded: '2010',
      headquarters: 'Sydney, Australia',
      website: 'https://epsilonenergy.com',
      logo: 'https://logo.clearbit.com/epsilonenergy.com',
      employees: 2200,
      revenue: '$400M',
      type: 'Private',
      specialties: ['Solar', 'Wind'],
      benefits: ['Flexible hours'],
      culture: ['Green', 'Innovative'],
      technologies: ['Python', 'SCADA'],
      locations: [{ city: 'Sydney', state: 'NSW', country: 'Australia', type: 'Headquarters' }],
      socialMedia: { linkedin: '', twitter: '' },
      ratings: { overall: 4.2, culture: 4.3, workLifeBalance: 4.2, careerGrowth: 4.1, compensation: 4.0, management: 4.1, totalReviews: 300 },
      contactInfo: { email: '', phone: '' },
      scrapedAt: new Date().toISOString(),
      source: 'Hardcoded'
    },
    {
      id: 'company_6',
      name: 'Zeta Logistics',
      description: 'Efficient logistics and supply chain solutions.',
      industry: 'Logistics',
      size: '3,000+ employees',
      founded: '2008',
      headquarters: 'Singapore',
      website: 'https://zetalogistics.com',
      logo: 'https://logo.clearbit.com/zetalogistics.com',
      employees: 3500,
      revenue: '$600M',
      type: 'Private',
      specialties: ['Supply Chain', 'Warehousing'],
      benefits: ['Health insurance'],
      culture: ['Efficient', 'Global'],
      technologies: ['Java', 'SAP'],
      locations: [{ city: 'Singapore', state: '', country: 'Singapore', type: 'Headquarters' }],
      socialMedia: { linkedin: '', twitter: '' },
      ratings: { overall: 4.0, culture: 4.0, workLifeBalance: 4.0, careerGrowth: 4.0, compensation: 4.0, management: 4.0, totalReviews: 400 },
      contactInfo: { email: '', phone: '' },
      scrapedAt: new Date().toISOString(),
      source: 'Hardcoded'
    },
    {
      id: 'company_7',
      name: 'Theta Finance',
      description: 'Financial services for the digital age.',
      industry: 'Finance',
      size: '8,000+ employees',
      founded: '2000',
      headquarters: 'Zurich, Switzerland',
      website: 'https://thetafinance.com',
      logo: 'https://logo.clearbit.com/thetafinance.com',
      employees: 8500,
      revenue: '$1.5B',
      type: 'Public',
      specialties: ['Banking', 'Investments'],
      benefits: ['401k', 'Health insurance'],
      culture: ['Stable', 'Professional'],
      technologies: ['.NET', 'Oracle'],
      locations: [{ city: 'Zurich', state: '', country: 'Switzerland', type: 'Headquarters' }],
      socialMedia: { linkedin: '', twitter: '' },
      ratings: { overall: 4.1, culture: 4.0, workLifeBalance: 4.0, careerGrowth: 4.0, compensation: 4.1, management: 4.0, totalReviews: 900 },
      contactInfo: { email: '', phone: '' },
      scrapedAt: new Date().toISOString(),
      source: 'Hardcoded'
    },
    {
      id: 'company_8',
      name: 'Lambda Foods',
      description: 'Innovative food products for a changing world.',
      industry: 'Food & Beverage',
      size: '4,000+ employees',
      founded: '2012',
      headquarters: 'Paris, France',
      website: 'https://lambdafoods.com',
      logo: 'https://logo.clearbit.com/lambdafoods.com',
      employees: 4200,
      revenue: '$350M',
      type: 'Private',
      specialties: ['Vegan', 'Organic'],
      benefits: ['Free meals'],
      culture: ['Healthy', 'Innovative'],
      technologies: ['ERP'],
      locations: [{ city: 'Paris', state: '', country: 'France', type: 'Headquarters' }],
      socialMedia: { linkedin: '', twitter: '' },
      ratings: { overall: 4.2, culture: 4.3, workLifeBalance: 4.2, careerGrowth: 4.1, compensation: 4.0, management: 4.1, totalReviews: 250 },
      contactInfo: { email: '', phone: '' },
      scrapedAt: new Date().toISOString(),
      source: 'Hardcoded'
    },
    {
      id: 'company_9',
      name: 'Sigma Telecom',
      description: 'Telecom solutions for the modern world.',
      industry: 'Telecommunications',
      size: '7,000+ employees',
      founded: '1990',
      headquarters: 'Tokyo, Japan',
      website: 'https://sigmatelecom.com',
      logo: 'https://logo.clearbit.com/sigmatelecom.com',
      employees: 7500,
      revenue: '$1.2B',
      type: 'Public',
      specialties: ['Mobile', 'Internet'],
      benefits: ['Health insurance'],
      culture: ['Tech-driven'],
      technologies: ['C', 'Linux'],
      locations: [{ city: 'Tokyo', state: '', country: 'Japan', type: 'Headquarters' }],
      socialMedia: { linkedin: '', twitter: '' },
      ratings: { overall: 4.0, culture: 4.0, workLifeBalance: 4.0, careerGrowth: 4.0, compensation: 4.0, management: 4.0, totalReviews: 600 },
      contactInfo: { email: '', phone: '' },
      scrapedAt: new Date().toISOString(),
      source: 'Hardcoded'
    },
    {
      id: 'company_10',
      name: 'Omega Media',
      description: 'Media and entertainment for the digital era.',
      industry: 'Media',
      size: '2,500+ employees',
      founded: '2015',
      headquarters: 'Los Angeles, USA',
      website: 'https://omegamedia.com',
      logo: 'https://logo.clearbit.com/omegamedia.com',
      employees: 2700,
      revenue: '$200M',
      type: 'Private',
      specialties: ['Streaming', 'Content'],
      benefits: ['Free snacks'],
      culture: ['Creative'],
      technologies: ['Node.js', 'React'],
      locations: [{ city: 'Los Angeles', state: 'CA', country: 'USA', type: 'Headquarters' }],
      socialMedia: { linkedin: '', twitter: '' },
      ratings: { overall: 4.1, culture: 4.2, workLifeBalance: 4.1, careerGrowth: 4.0, compensation: 4.0, management: 4.0, totalReviews: 350 },
      contactInfo: { email: '', phone: '' },
      scrapedAt: new Date().toISOString(),
      source: 'Hardcoded'
    },
    // ... 10 more companies for this batch ...
  ];

  return companies;
}; 